/****************************************************
* guess -- a simple guessing game
******************************************************
Usage:
* guess
******************************************************
A random number is chosen between 1 and 100.
* The player is given a set of bounds and
* must choose a number between them.
* If the player chooses the correct number, he wi
* Otherwise the bounds are adjusted to reflect
* the players guess and the game continues
******************************************************
Restrictions:
* The random number is generated by the statment
* rand( ) % 100. Because rand( ) returns a num
* 0 <= rand( ) <= maxint this slightly favors
* the lower numbers.
***************************************************/

#include <iostream>
#include <cstdlib>

using namespace std;

int number_to_guess;    //random number to be guessed
int low_limit;          //current lower limit of play
int high_limit;         //current upper limit of play
int guess_count;        //no of times played guess
int player_no;          //no gotten from the player

int main(){
    while (true)
    {
        /* Not a pure no, see restriction */
        number_to_guess = rand() % 100 + 1;

        //Initialize var for loop
        low_limit = 0;
        high_limit = 100;
        guess_count = 0;

        while (true)
        {
            /* Tell the player what the bounds are and get a guess */
            cout << "Bounds " << low_limit << " - " << high_limit << "\n";
            cout << "Guess count " << guess_count << "\n";

            ++guess_count;      //increment guess count

            cout << "Enter a guess(1000 to exit program): ";
            cin >> player_no;

            //did he guess right ?
            if (player_no == number_to_guess)
                break;
            else if (player_no < number_to_guess)
            {
                //adjust bounds for next guess
                low_limit = player_no;
            }
            else if (player_no == 1000)
            {
                /* exit program */
                break;
            }
            
            else
            {
                high_limit = player_no;
            }
            
            

        }
        if (player_no == 1000)
            //exit program
            break;
        else
            cout << "Bingo\n";
            
        
        

        
    }
    return (0);
}
